title: Katerina's blog
author: Katerina
description: > # this means to ignore newlines until "baseurl:"
  How am I learning programming and what I have done so far :)

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
